#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Resume.Droid.Resource", IsApplication=true)]

namespace Resume.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int pressed_resume = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_resume = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_resume = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_resume = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_resume = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_resume = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_resume = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int app_icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_default_resume = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_focused_resume = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_pressed_resume = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_cab_done_resume = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_bottom_resume = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cab_background_top_resume = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int daniel = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int drawer_shadow_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int header_info = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_drawer_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ico_education = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ico_menu_arrow = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ico_work = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int list_focused_resume = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int list_item_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int list_item_pressed_transparent = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int menu_dropdown_panel_resume = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int pressed_background_resume = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int progress_bg_resume = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int progress_horizontal_resume = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int progress_primary_resume = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int progress_secondary_resume = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int selectable_background_resume = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int spinner_ab_default_resume = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int spinner_ab_disabled_resume = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int spinner_ab_focused_resume = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int spinner_ab_pressed_resume = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int spinner_background_ab_resume = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_indicator_ab_resume = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_selected_focused_resume = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tab_selected_pressed_resume = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tab_selected_resume = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int tab_unselected_focused_resume = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int tab_unselected_pressed_resume = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int tab_unselected_resume = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070010
			public const int address = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int drawer_layout = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int education_list = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int email = 2131165197;
			
			// aapt resource value: 0x7f070007
			public const int experience_list = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int job_duration = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int job_location = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int job_name = 2131165192;
			
			// aapt resource value: 0x7f070015
			public const int left_drawer = 2131165205;
			
			// aapt resource value: 0x7f07000e
			public const int location = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int main = 2131165204;
			
			// aapt resource value: 0x7f07000b
			public const int name = 2131165195;
			
			// aapt resource value: 0x7f070016
			public const int navName = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int objective = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int phone_number = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int responsability = 2131165184;
			
			// aapt resource value: 0x7f070011
			public const int textView10 = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int textView11 = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int title = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int university = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int university_duration = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int university_location = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomListRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Education = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EducationRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Experience = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ExperienceRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int InfoLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MenuListItem = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int AddressTitle = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int DrawerClose = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int DrawerOpen = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int MenuItem1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int MenuItem2 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int MenuItem3 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int MenuItem4 = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int ObjectiveTitle = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ResumeUrl = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int SelectOption = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int SomethingWrong = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBar_Solid_Resume = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ActionBar_TitleTextStyle = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ActionBar_Transparent_Resume = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int ActionBarTabStyle_Resume = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int ActionButton_CloseMode_Resume = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int DropDownListView_Resume = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int DropDownNav_Resume = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int PopupMenu_Resume = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int ProgressBar_Resume = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Resume = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int Theme_Resume_Widget = 2131099658;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
